[package]
name = "juniper-actix"
version = "0.1.0"
authors = ["Nil Gradisnik <nil.gradisnik@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
log = "0.4"
env_logger = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.14"
rusqlite = "0.21"